position_source:
  type: static
  lat: 52
  lon: 10
# position_source:
#   type: dynamic
#   serial_device: /dev/ttyACM0


log_level: INFO
redis:
  host: localhost
  port: 6379
  stream_id: self
  output_stream_prefix: positionsource

prometheus_port: 8006